# Generated by Django 5.1.1 on 2024-12-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programschedule",
            name="bachelor_degree",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="programschedule",
            name="master_degree",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
